<?php

namespace app\api\controllers;

use app\api\components\BaseController;
use Codeception\Util\HttpCode;
use common\models\Taxonomy;
use common\models\Vehicle;
use yii\filters\ContentNegotiator;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use Yii;
use yii\web\Response;

class HomeController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     *
     * @OA\Get(
     *   path                   = "/home/",
     *   summary                = "Home Page List",
     *   tags                   = {"Home Page"},
     *
     *   @OA\Response(
     *     response             = 200,
     *     description          = "Returns all New Cars Suggested Vehicles",
     *   ),
     *     security={{
     *     "bearerAuth":{}
     *   }}
     * )
     */
    public function actionIndex(){
            $list = [];

            $list['makes'] = Taxonomy::getAllMakes();

            $list['suggested_vehicles'] = Vehicle::find()->all();

            return $list;

    }


    /**
     *
     * @OA\Get(
     *   path                   = "/home/create",
     *   summary                = "Test",
     *   tags                   = {"Home Page"},
     *
     *   @OA\Response(
     *     response             = 200,
     *     description          = "Returns Test Data",
     *   ),
     *
     * )
     */
    public function actionCreate(){
            return 'ss';

    }
}
