<?php


namespace frontend\controllers;


use yii\helpers\Url;
use yii\web\Controller;

class BaseController extends Controller
{
    public function isAr()
    {
        return \Yii::$app->language == "ar";
    }

    public function render($view, $params = [])
    {
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}