<?php

namespace common\components;

use Yii;

class BaseActiveRecord extends \yii\db\ActiveRecord
{
    public $project_base_path;

    public function init()
    {
        $this->project_base_path = Yii::$app->params['project_base_path'];
        if (property_exists($this, 'multiple_tbl')) {
            foreach ($this->multiple_tbl as $attribute => $config) {
//                if (in_array($this->scenario, $config['scenario']))
                    if (!isset($config['multiple_row']) || !$config['multiple_row']) {
                        $this->{$attribute} = new $config['model'](['scenario' => $this->scenario]);
                        $this->{$attribute}->loadDefaultValues();
                    }
            }
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function load($data, $formName = null)
    {
        if (property_exists($this, 'multiple_tbl')) {
            foreach ($this->multiple_tbl as $attribute => $config) {
                if ($data) {
                    $attributeFormName = isset($config['form_name']) ? $config['form_name'] : null;
                    if (!$this->{$attribute}){
                        $this->{$attribute} = new $config['model']();
                    }
                    $this->{$attribute}->load($data, $attributeFormName);
                }
            }
        }

        $load = parent::load($data, $formName);

        return $load;
    }
}