<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "company".
 *
 * @property int $user_id
 * @property string $name
 * @property string $name_en
 * @property string $vehicles_type
 * @property string|null $image
 * @property string|null $description
 * @property string|null $description_en
 * @property int|null $branch_number
 *
 * @property User $user
 */
class Company extends \common\models\BaseModels\Company
{
    public $imageFile ;
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public function rules()
    {
        return array_merge(parent::rules(),[
            [['imageFile'], 'file', 'extensions' => 'png, jpg','maxFiles' => 1],
            [['imageFile'],'file' , 'skipOnEmpty' => true , 'on' => self::SCENARIO_UPDATE, 'extensions' => 'png, jpg'],
            [['imageFile'], 'file' ,'skipOnEmpty' => false , 'on' => self::SCENARIO_CREATE, 'extensions' => 'png, jpg'],
        ]); // TODO: Change the autogenerated stub
    }

}
