<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "media".
 *
 * @property int $id
 * @property string $image
 * @property int $user_id
 *
 * @property User $user
 * @property VehicleMedia[] $vehicleMedia
 */
class Media extends \common\models\BaseModels\Media
{
    public $imageFile;
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';

    public function rules()
    {
        return array_merge(parent::rules(),[
            [['imageFile'], 'file', 'extensions' => 'png, jpg','maxFiles' => 6 , 'extensions' => 'png, jpg, jpeg' ],
            [['imageFile'],'file' , 'skipOnEmpty' => true , 'on' => self::SCENARIO_UPDATE],
            [['imageFile'], 'file' ,'skipOnEmpty' => false , 'on' => self::SCENARIO_CREATE],
        ]); // TODO: Change the autogenerated stub
    }
}
