<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "media".
 *
 * @property int $id
 * @property string $image
 * @property int $user_id
 *
 * @property User $user
 * @property VehicleMedia[] $vehicleMedia
 */
class Media extends \common\models\BaseModels\Media
{
    public $imageFile;
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';

    public function rules()
    {
        return array_merge(parent::rules(),[
            [['imageFile'], 'file', 'extensions' => 'png, jpg,  jpeg, webp','maxFiles' => 6],
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $s3 = Yii::$app->S3;
        $this->image  = $s3->getUrl($this->image);
        parent::afterFind();
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert);
    }
}
