<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "vehicle".
 *
 * @property int $id
 * @property int $user_id
 * @property int $make_id
 * @property int $model_id
 * @property int $color_id
 * @property int $body_type_id
 * @property int $gear_box_id
 * @property string $title
 * @property string $title_en
 * @property string $price
 * @property string $description
 * @property string $description_en
 * @property string $main_image
 * @property string $type
 * @property string|null $status
 * @property string|null $manufacturing_year
 * @property int|null $is_deleted
 * @property string|null $created_at
 * @property string|null $updated_at
 *
 * @property NewVehicle $newVehicle
 * @property UsedVehicle $usedVehicle
 * @property Taxonomy $bodyType
 * @property Taxonomy $color
 * @property Taxonomy $gearBox
 * @property Taxonomy $make
 * @property Taxonomy $model
 * @property User $user
 * @property VehicleComment[] $vehicleComments
 * @property Comment[] $comments
 * @property VehicleFeature[] $vehicleFeatures
 * @property Taxonomy[] $taxonomies
 * @property VehicleMedia[] $vehicleMedia
 */
class Vehicle extends \common\models\BaseModels\Vehicle
{
    public $imageFile;
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    const TYPE_NEW = 'new';
    const TYPE_USED = 'used';

    public function rules()
    {
        return array_merge(parent::rules(),[
            [['imageFile'], 'file', 'extensions' => 'png, jpg','maxFiles' => 1 , 'extensions' => 'png, jpg, jpeg' ],
            [['imageFile'],'file' , 'skipOnEmpty' => true , 'on' => self::SCENARIO_UPDATE],
            [['imageFile'], 'file' ,'skipOnEmpty' => false , 'on' => self::SCENARIO_CREATE],
        ]); // TODO: Change the autogenerated stub
    }

    public function vehicleTypeList(){
        return [
            self::TYPE_NEW => Yii::t('app' , 'new'),
            self::TYPE_USED => Yii::t('app' , 'used')
        ];
    }

    public function beforeSave($insert)
    {
        if($this->imageFile = UploadedFile::getInstance($this,'imageFile')){
            $this->main_image = $this->imageFile->name;
            if(!$this->imageFile->saveAs('uploads/company/'.time() .'_' .$this->imageFile)){
                return false;
            }
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
